<a href="https://colab.research.google.com/github/hardiksharma6555/MLP_code/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[0,0],[1,1],[2,2],[3,3]])
y = np.dot(X, np.array([1,1]))-1

In [ ]:
y

array([-1,  1,  3,  5])

In [ ]:
reg = LinearRegression().fit(X,y)
reg.predict(np.array([[5,6]]))

array([10.])

In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
... ]
vectorizer = HashingVectorizer(n_features=2**4)
X = vectorizer.fit_transform(corpus)
print(X.shape)

AttributeError: ignored

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X,y = load_iris(as_frame = True, return_X_y = True)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 test_size = 0.2,
                                                 random_state = 1)
clf = DecisionTreeClassifier(max_features=2,
                             max_depth = 6,
                             min_samples_split = 2,
                             min_samples_leaf = 3,
                             random_state = 81)

In [ ]:
clf.fit(X_train,y_train)
print(clf)

DecisionTreeClassifier(max_depth=6, max_features=2, min_samples_leaf=3,
                       random_state=81)


In [ ]:
import numpy as np
from sklearn.dummy import DummyRegressor
X = np.array([1.0,1.0,1.0])
y = np.array([1.5,1.5,1.5])
dummy_regr = DummyRegressor(strategy = "mean")
dummy_regr.fit(X,y)
dummy_regr.predict(X)

array([1.5, 1.5, 1.5])